import React, { createContext, useContext, useState, useEffect } from 'react';
import { fetchLanguagePreference, saveLanguagePreference } from '../services/themeApi';

export type Language = 'en' | 'zh';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Chinese UI copy — zh mode shows pure Chinese; en mode shows English keys unchanged.
const zhTranslations: Record<string, string> = {
  // Navigation & Sidebar
  "New Chat": "新建会话",
  "Chat": "会话",
  "Agents": "智能体",
  "Flows": "流程",
  "Agent": "智能体",
  "Flow": "流程",
  "Project": "项目",
  "Set": "设置",
  "New Chat / Reset": "重置",
  "AI Agents": "AI 智能体",
  "Design": "设计",
  "Coding": "编码",
  "Language": "语言",
  "Welcome to Design": "欢迎使用 Design",
  "What do you want to design?": "你想设计什么？",
  "Paste or attach a reference image": "粘贴或上传参考图，即可生成设计规范与界面",
  "Attach Design.md, a website URL, or a reference image": "可上传 Design.md、粘贴网址，或附上参考图",
  "Design system": "设计系统",
  "Built-in Clutch design system — clean developer-tool aesthetic": "内置 Clutch 设计规范 — 干净克制的开发者工具美学",
  "Reference attachment overrides the design system preset.": "已附参考素材，将按参考提取设计风格，不使用内置预设。",
  "Describe changes, or send to match the reference": "描述改动，或直接发送以按参考生成",
  "Match this reference UI": "按参考图生成界面",
  "Remove reference image": "移除参考图",
  "Remove file": "移除文件",
  "Remove URL": "移除网址",
  "Reference": "参考图",
  "Add attachment": "添加附件",
  "Website URL": "网站网址",
  "Upload file": "上传文件",
  "Upload image": "上传图片",
  "Paste URL…": "粘贴网址…",
  "Add URL": "添加",
  "Web": "网页",
  "App": "应用",
  "New Design": "新建设计",
  "Crafting the design…": "正在构思设计…",
  "Generating…": "生成中…",
  "Generating interface…": "正在生成界面…",
  "Designing…": "设计中…",
  "Crafting…": "构思中…",
  "Crafting design system…": "正在构思设计系统…",
  "Sketching…": "描绘中…",
  "Sketching interface…": "正在描绘界面…",
  "Updating…": "更新中…",
  "What do you want to change or create?": "你想修改或创建什么？",
  "Select a card, then describe the change…": "先选中画布卡片，再描述要改或新增的内容…",
  "Pick element": "点选元素",
  "Picking…": "点选中…",
  "Click a component": "点击画板中的组件",
  "Artboard": "画板",
  "Selected": "已选",
  "Element": "元素",
  "Clear selection": "清除选中",
  "Clear element": "清除元素",
  "Create another screen based on the selection": "基于选中界面再创建一个新页面",
  "Design specification": "设计规范",
  "Project name": "项目名称",
  "New project": "新建项目",
  "No design projects yet": "暂无设计项目",
  "Authorize a workspace to use Design": "请先授权工作区以使用 Design",
  "Back to Chat": "返回对话",
  "Describe the product or user journey…": "描述产品或用户旅程…",
  "Generate prototype": "生成原型",
  "Vision": "视觉参考",
  "Upload screenshot or sketch": "上传截图或草图",
  "Play": "播放",
  "Exit Play": "退出播放",
  "Approve": "批准",
  "Create or open a Design project": "创建或打开设计项目",
  "Prototype → Approve → UI code → Coding": "原型 → 批准 → 界面代码 → 编码",
  "Iterate this screen…": "迭代当前屏幕…",
  "Iterate": "迭代",
  "Preview": "预览",
  "UI code": "界面代码",
  "Next steps": "下一步",
  "Prototype ready — continue to UI code": "原型已完成 — 继续生成界面代码",
  "Open next steps": "打开下一步",
  "Approve prototype to unlock UI code": "先批准原型，再生成界面代码",
  "Generate React + Tailwind from this prototype": "从当前原型生成 React + Tailwind 代码",
  "Preview and approve UI code, then send to Coding": "预览并批准界面代码，再交给编码",
  "Send approved UI code to a Coding session": "将已批准的界面代码交给 Coding 会话",
  "Select a screen to preview": "选择屏幕以预览",
  "Prototype approved. Generate a Vite + React + Tailwind app.": "原型已批准。可生成 Vite + React + Tailwind 应用。",
  "Approve the prototype first.": "请先批准原型。",
  "Generate UI code": "生成界面代码",
  "Start preview": "启动预览",
  "Approve UI code": "批准界面代码",
  "Send to Coding": "交给编码",
  "Working…": "处理中…",
  "Prototype": "原型",
  "Branch": "分支",
  "Not a git repository": "非 Git 仓库",
  "Model": "模型",
  "Engine": "驱动引擎",
  "Model is provided by the selected agent tool": "模型由所选 Agent 工具自带",
  "Workflow": "工作流",
  "System Preferences": "系统设置",
  "Status Overview": "状态概览",
  "Active Preset Themes": "活跃 主题",
  "Available Preset Themes": "可用 主题预设",
  "Workspace:": "工作空间:",
  "Session:": "会话:",
  "ACTIVE": "活跃",
  "STYLING ENGINE OK": "样式引擎正常",
  "REPOSITORIES": "源码仓库",
  "General": "通用",
  "General Settings": "通用设置",
  "Customize your application profile, account settings and default preferences.": "自定义您的应用个人资料、帐户设置和默认偏好。",
  "Profile Avatar": "个人头像",
  "Profile Name": "个人名称",
  "Font Size": "字体大小",
  "Small": "小",
  "Default": "默认",
  "Large": "大",
  "Extra Large": "特大",
  "Super Large": "超级大",
  "Enter your name": "输入您的名称",
  "Choose Photo": "选择照片",
  "Reset to Default": "重置为默认",
  "Supported formats: PNG, JPG, GIF. Max file size: 5MB.": "支持格式：PNG、JPG、GIF。文件大小限制：5MB。",
  "AI Tools": "AI 工具",
  "Models Config": "模型配置",
  "Skills Registry": "技能注册表",
  "MCP Server Hub": "MCP 服务网关",
  "Appearance": "外观配置",
  "Feature under active development": "功能正在积极开发中",
  "New version available: {{version}}": "发现新版本：{{version}}",
  "Update": "更新",
  "Restart": "重启",
  "Download update": "下载更新",
  "Downloading... {{done}} / {{total}} ({{percent}}%)": "下载中… {{done}} / {{total}}（{{percent}}%）",
  "Update {{version}} downloaded.": "更新 {{version}} 已下载。",
  "Update {{version}} downloaded. Restart to install.": "更新 {{version}} 已下载，请重启安装。",
  "Restart to install": "重启安装",
  "Later": "稍后",
  "Update download failed. Check your connection and try again.": "下载更新失败，请检查网络后重试。",
  "Update install failed. Try again or download from GitHub Releases.": "安装更新失败，请重试或从 GitHub Releases 手动下载。",
  "Update ready": "更新已就绪",
  "Runtime update ready": "运行时更新已就绪",
  "A runtime update is ready. Apply now? The orchestrator will restart briefly; the current chat may be interrupted.": "运行时更新已就绪，是否立即应用？（将短暂重启编排服务，当前对话可能中断）",
  "Apply": "应用",
  "Active Palette Scheme:": "活跃配色方案:",
  "Active Theme": "活跃 主题",
  "Updates all buttons, panels, background layout variables, and typography states.": "刷新工作空间界面各布局组件、按钮面板及排版颜色状态。",
  "Customize the developer workspace environment with cohesive colors, borders, shadows, and eye-friendly presets.": "定制开发工作空间环境，包含协调的色彩、边框、阴影和对眼部友好的预设。",
  "Workspace Theme Configurator": "工作空间 主题配置器",

  // Model Config page
  "AI Workspace Models": "AI 模型中心",
  "Monitor, connect, and configure Large Language Models for active agent execution, reasoning logic, and prompt engineering.": "监视、连接和配置大语言模型，用于智能体执行、推理逻辑和提示词工程。",
  "Add External Model Provider": "添加外部 模型提供商",
  "Integration Hub": "集成中心",
  "Connect External Model Provider": "连接外部 模型提供商",
  "Model Name / Identifier": "模型标识符",
  "Provider Platform": "提供商平台",
  "Local Ollama Integration Guide": "本地 Ollama 集成指南",
  "Then run your model, for example:": "然后运行您的模型，例如：",
  "Custom Provider Name": "自定义提供商名称",
  "API Endpoint URL (Optional)": "API 端点 URL (可选)",
  "API Key / Credentials (Optional)": "凭据 (可选)",
  "Context Window Spec": "上下文窗口规格",
  "Default Temperature": "默认 Temperature温度",
  "Model Notes / Purpose": "模型备注与用途",
  "Save & Connect Model": "保存并连接 模型",
  "Cancel": "取消",
  "Configured & Connected Models": "已配置与已连接的 模型",
  "Installed": "已安装",
  "Active LLM Orchestrator:": "活跃 LLM Orchestrator大模型编排器:",
  "PROVIDER SYNCED": "提供方已同步",
  "Activate Mode": "激活 模型",

  // Chat placeholders / messages
  "Note: These settings only apply to the built-in Clutch Agent and MCP tools, and do not affect CLI Agents (such as Claude Code).": "提示：此权限模式仅适用于内置 Clutch 智能体与 MCP 工具，不影响 CLI 智能体（如 Claude Code）。",
  "@Agent your feedback (Hybrid) — auto-continues downstream; Stop to pause": "@Agent 反馈修改意见（Hybrid）— 精修后自动继续；可先停止再改",
  "Ask @Agent or describe your workflow...": "向 @Agent 提问，或描述工作流任务…",
  "Ask your AI Agent anything...": "向 AI 智能体提问…",
  "View execution details": "查看底层执行细节",
  "Shell command": "Shell 命令",
  "System prompt": "系统提示词",
  "Boundary marker": "边界标记",
  "Raw shell output": "原始 Shell 输出",
  "No structured execution details were captured for this turn.": "本轮未捕获结构化执行细节",
  "sections": "项",
  "Expand": "展开",
  "Collapse": "收起",
  "Run Workflow": "运行工作流",
  "Run SOP": "运行 SOP",
  "Start a supervised session": "开始新的监督会话",
  "What should we do in {name}?": "我们应该在{name}中做些什么？",
  "Explore and understand the code": "探索并理解代码",
  "Build new features, apps or tools": "构建新功能、应用或工具",
  "Review code and propose changes": "审查代码并提出修改建议",
  "Fix issues and failures": "修复问题和失败",
  "Explore this codebase and explain the overall architecture.": "探索这个代码库，讲解整体架构。",
  "Build a new feature: ": "构建一个新功能：",
  "Review the recent code changes and propose improvements.": "审查最近的代码改动并提出修改建议。",
  "Find and fix a bug or failing behavior.": "查找并修复一个问题或失败的行为。",
  "Select a workspace and start a workflow, or type an instruction below. Clutch will orchestrate AI Agents and ask for your approval when needed.": "选择工作区并启动工作流，或直接在下方输入指令。Clutch 会编排 AI 智能体，并在需要时请你审批。",
  "Start a single agent session": "开始单智能体会话",
  "Select a workspace and type an instruction below to chat with the agent directly.": "选择工作区并在下方输入指令，直接与智能体进行对话。",
  "Authorize workspace": "授权工作区",
  "Choose workflow template": "选择工作流模板",
  "Create Flow": "创建工作流",
  "Add Node": "添加节点",
  "Save Flow": "保存工作流",
  "Saving...": "保存中…",
  "Save Node": "保存节点",
  "Selected for chat": "已选中 · 用于 Chat",
  "No workflows yet": "暂无工作流",
  "Manage workflows...": "管理工作流...",
  "Manage models...": "管理模型...",
  "Manage agents...": "管理 Agent...",
  "No models configured": "暂无已配置模型",
  "View workflow": "查看工作流",
  "Edit workflow": "编辑工作流",
  "Edit Workflow": "编辑工作流",
  "Create New Workflow": "创建新工作流",
  "Delete workflow": "删除工作流",
  "Empty workflow — click Add Node to begin": "空工作流 — 点击 Add Node 开始编排",
  "Describe what you want this workflow to do...": "描述你希望此工作流完成的任务…",
  "Clear": "清除",
  "Workflow running": "工作流运行中",
  "Chat mode": "对话模式",
  "Terminal mode": "终端模式",
  "Leave terminal mode?": "离开终端模式？",
  "Leaving terminal mode will end the current session and keep only handoff and dispatch records. Continue?": "离开后，当前终端会话将结束，仅保留 handoff 与调度记录。确定要离开吗？",
  "Terminal history banner": "此会话为终端调度历史记录。终端已关闭，仅可查看 handoff 文件与调度记录。",
  "Terminal history read-only placeholder": "历史会话只读，无法继续调度",
  "Historical session is read-only": "历史会话只读，无法继续调度",
  "Terminal dispatch executed": "任务已在终端中执行",
  "Read-only": "只读",
  "Handoff": "Handoff",
  "Handoff overview tip": "在终端之间传递上下文时，系统会生成 handoff 文件并记录在此。",
  "Dispatch records": "调度记录",
  "No dispatch records yet": "暂无调度记录",
  "Preview handoff": "预览 handoff",
  "Send to Bar": "填入输入框",
  "Graph": "图谱",
  "Natural": "自然语言",
  "Orchestrator input placeholder": "输入 @Agent 指令，或从右侧选择 handoff 记录…",
  "Mention an agent to open a terminal": "输入 @Agent 以打开终端",
  "Type @Agent in the bar below to launch that agent's CLI. Clear the mention to close the terminal pane.": "在下方输入框输入 @Agent 即可加载对应 CLI 终端；清除 @ 提及后终端会收起。",
  "Example prompts": "示例指令",
  "Summarize this repo and list open tasks": "总结本仓库并列出待办事项",
  "from": "来自",
  "Continue the API implementation": "继续实现 API",
  "Background terminals: {count} total": "后台终端共 {count} 个",
  "Close other terminals": "关闭其他终端",
  "Close terminal": "关闭终端",
  "Terminal session IDs": "终端会话 ID",
  "View in terminal": "在终端中查看",
  "Hide terminal command": "收起命令",
  "Session ID": "会话 ID",
  "Copy command": "复制命令",
  "Run this in your system terminal from the same project directory Clutch used. Restores the Claude Code session. If unsure, run claude (no args) or use /resume in the CLI picker.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录），恢复 Claude Code 会话。必须在同一项目目录下运行；不确定时可先运行 claude（无参数）或在 CLI 内使用 /resume 选择会话。",
  "Run this in your system terminal from the same project directory Clutch used. Restores the CodeBuddy session.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录），恢复 CodeBuddy 会话。必须在同一项目目录下运行。",
  "Run this in your system terminal from the same project directory Clutch used. Restores the Codex session by ID.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录），通过会话 ID 恢复 Codex 会话。",
  "Run this in your system terminal from the same project directory Clutch used. Restores the OpenCode session by ID.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录），通过会话 ID 恢复 OpenCode 会话。",
  "Run this in your system terminal from the same project directory Clutch used. Continues the most recent OpenCode session in that folder (opencode -c). Run opencode session list to pick a specific session.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录）。在该目录下继续最近一次 OpenCode 会话（opencode -c）；如需指定会话，可先运行 opencode session list。",
  "Run this in your system terminal from the same project directory Clutch used. Continues the most recent Codex session in that folder (codex resume --last). Run codex resume to pick from history.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录）。在该目录下继续最近一次 Codex 会话（codex resume --last）；也可运行 codex resume 从历史中选择。",
  "Run this in your system terminal from the same project directory Clutch used. Open Antigravity CLI and pick the conversation from its session list.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录）。打开 Antigravity CLI 后从会话列表中选择对应对话。",
  "Run this in your system terminal from the same project directory. Rivet does not support resuming by session ID — open the TUI and pick the conversation in its session list.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录）。Rivet 不支持按会话 ID 恢复 — 打开 TUI 后在会话列表中选择对应对话。",
  "Run Aider in your system terminal from the same project directory. Aider resumes via chat-history files, not session IDs — start aider and use --restore-chat-history if you saved history.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录）。Aider 通过聊天历史文件恢复，不支持会话 ID — 启动 aider 后如有保存的历史可使用 --restore-chat-history。",
  "Ollama has no session resume by ID. Run ollama in your system terminal from the project directory to continue interacting with the model.": "Ollama 不支持按会话 ID 恢复。在系统终端从项目目录运行 ollama 以继续与模型交互。",
  "Run this in your system terminal from the same project directory Clutch used. Restores the Antigravity CLI session.": "在系统终端运行此命令（会先 cd 到 Clutch 终端使用的工作区目录），恢复 Antigravity CLI 会话。必须在同一项目目录下运行。",
  "Open the matching Agent CLI in your system terminal to browse session history.": "在系统终端打开对应 Agent CLI 以浏览会话历史。",
  "Terminal console": "终端控制台",
  "Interactive CLI ready": "交互 CLI 已就绪",
  "Connecting interactive CLI…": "正在连接交互 CLI…",
  "Opening terminal…": "正在打开终端…",
  "Terminal pages": "终端分页",
  "Terminal page": "终端页",
  "Read-only audit log (interactive PTY unavailable)": "只读审计日志（交互 PTY 不可用）",
  "SIDECAR IDLE": "SIDECAR 空闲",
  "Receiving sidecar events": "监督台正在接收 Sidecar 事件…",
  "Human gate hint": "检查未通过或需要人工确认，请选择下一步操作。",
  "Retry instructions placeholder": "附加指令，例如 \"跳过语法检查直接打包\"",
  "No active workflow overview": "暂无运行中的工作流。启动模板或发送指令后，这里会显示 Token 统计与 Flow 进度。",
  "No session activity yet": "开始与 Agent 对话后，这里会显示会话状态与 Token 统计。",
  "Workflow step execution": "工作流步骤执行",
  "Workflow steps unavailable": "无法加载工作流步骤定义。",
  "Workflow selected — send a message to start": "已选择工作流 — 发送消息即可启动",
  "Uncommitted changes": "未提交变更",
  "No uncommitted changes": "暂无未提交变更。",
  "Terminal logs": "终端日志",
  "Authorize workspace files hint": "请先在侧栏添加项目文件夹，或点击 Authorize workspace。",
  "Workspace folder empty": "工作区为空。",
  "No terminal logs yet": "暂无日志。Coding 工作流或 Design 生成开始后，输出会显示在这里。",
  "Session tokens accumulated": "本轮累计",
  "Select project folder": "选择项目根目录",
  "Add project folder": "添加项目文件夹",
  "New project group": "新建项目分组",
  "Filter projects": "筛选项目",
  "No projects in this group yet": "此分组下暂无项目",
  "No projects match your filter": "没有匹配筛选条件的项目",
  "No repositories yet. Use Add project folder or Authorize workspace to begin.": "尚无项目。请通过侧栏添加文件夹，或点击 Authorize workspace。",
  "New session": "新建会话",
  "Loading session": "正在加载会话",
  "Projects": "项目",
  "No sessions in this project yet": "此项目下暂无会话",
  "Saved workspace snapshot": "已保存工作环境快照",
  "Continue previous work": "可继续上次工作",
  "Select a project before starting a conversation.": "请先选择项目，再开始对话。",
  "Are you sure you want to remove this project from the list?": "确定要从列表中移除该项目吗？",
  "Are you sure you want to permanently delete this session?": "确定要永久删除该会话吗？",
  "Delete": "删除",
  "Delete message": "删除消息",
  "Delete project": "删除项目",
  "Delete session": "删除会话",
  "Enter group name...": "请输入分组名称...",
  "Confirm": "确认",
  "Reload": "重新加载",
  "Thinking...": "思考中...",
  "Queued for shell...": "排队等待 shell…",
  "Clutch Agent": "Clutch 智能体",
  "Settings": "设置",
  "Default Group": "默认分组",
  "Move to Group": "移动至分组",
  "Rename Group": "重命名分组",
  "Delete Group": "删除分组",
  "Rename": "重命名",
  "Are you sure you want to delete this group?": "确定要删除该分组吗？",
  "Enter new group name...": "请输入新的分组名称...",

  // Onboarding
  "Welcome to Clutch": "欢迎使用 Clutch",
  "Local AI multi-agent orchestration for developers — supervise workflows, not black boxes.": "面向开发者的本地 AI 多智能体编排工具：监督工作流，而不是面对黑盒。",
  "Environment requirements": "环境检查",
  "✓ Met  ·  ⚠ Recommendation (you can continue)  ·  ℹ Informational only": "✓ 已满足  ·  ⚠ 建议项（可继续）  ·  ℹ 仅供参考",
  "macOS 14+ or Windows 10/11 x64": "macOS 14+ 或 Windows 10/11 x64",
  "Apple Silicon Mac or Windows x64 build recommended": "建议使用 Apple Silicon Mac 或 Windows x64 构建",
  "~500 MB disk space for app data": "约 500 MB 可用磁盘空间用于应用数据",
  "Network required for cloud LLM providers": "云端大模型服务需要网络连接",
  "Unsigned installer: allow only after verifying the download": "未签名安装包：确认来源后再允许运行",
  "Your operating system meets our recommendation.": "当前操作系统符合推荐要求。",
  "Unsupported or less-tested operating system detected — Clutch may still run, but packaging support is limited.": "检测到未充分测试的操作系统。Clutch 可能仍可运行，但安装包支持有限。",
  "Could not verify the operating system version. macOS 14+ or Windows 10/11 x64 is recommended.": "无法确认操作系统版本。推荐使用 macOS 14+ 或 Windows 10/11 x64。",
  "Recommended architecture detected for this package.": "检测到适合当前安装包的系统架构。",
  "Less-tested CPU architecture detected — Clutch may still run, but this package is optimized for Apple Silicon or Windows x64.": "检测到测试较少的处理器架构。Clutch 可能仍可运行，但当前安装包主要面向 Apple Silicon 或 Windows x64。",
  "Architecture could not be fully verified. Windows ARM may run the x64 build through emulation.": "无法完整确认系统架构。Windows ARM 可能会通过模拟运行 x64 构建。",
  "Enough storage available for app data.": "可用空间足够保存应用数据。",
  "Low storage — saving workspace or preferences may fail. Free up ~500 MB.": "磁盘空间偏低；保存工作区或偏好设置可能失败。请至少释放约 500 MB。",
  "Could not measure free disk space. Please keep ~500 MB available.": "无法检测可用磁盘空间。请预留约 500 MB。",
  "Online — you can configure cloud LLM providers.": "网络可用，可以配置云端大模型服务。",
  "Offline or no internet — skip cloud models and use a local CLI instead.": "当前离线或无法访问网络；可跳过云端模型，改用本地 CLI。",
  "Network probe was inconclusive. If your browser can access your model provider, you can continue.": "网络探测结果不确定。如果浏览器可以访问你的模型服务商，可以继续。",
  "Clutch is running — installer advisory passed.": "Clutch 已运行，安装包提示已通过。",
  "If macOS Gatekeeper or Windows SmartScreen blocks launch, verify the package source and see INSTALL.md.": "如果 macOS Gatekeeper 或 Windows SmartScreen 拦截启动，请先确认安装包来源，并查看 INSTALL.md。",
  "Checking environment…": "正在检查环境…",
  "Yellow items are recommendations only — not blockers. You can continue once Sidecar is ready.": "黄色项目只是建议项，不会阻止继续。Sidecar 就绪后即可进入下一步。",
  "Waiting for Clutch sidecar…": "正在等待 Clutch Sidecar…",
  "Sidecar ready": "Sidecar 已就绪",
  "Sidecar not ready": "Sidecar 尚未就绪",
  "See INSTALL.md §8 for troubleshooting": "排障说明见 INSTALL.md 第 8 节",
  "Retry": "重试",
  "Continue": "继续",
  "Back": "返回",
  "Launching…": "正在启动…",
  "Launch workspace →": "进入工作区 →",
  "Onboarding model or tools required": "请至少配置一个模型或连接一个本地工具",
  "Could not finish onboarding": "无法完成初始化",
  "Choose your workspace": "选择工作区",
  "Clutch reads and writes only inside the project folder you authorize.": "Clutch 只会在你授权的项目文件夹内读取和写入。",
  "Use Clutch.app to complete first-time setup": "请在 Clutch 桌面应用中完成首次设置",
  "Workspace authorize failed": "工作区授权失败",
  "Selected": "已选择",
  "Selecting…": "正在选择…",
  "Connect a cloud model": "连接云端模型",
  "Onboarding models skip hint": "可先连接一个云端模型；如果你更想用本地 CLI，也可以暂时跳过。",
  "Enter an API key for this provider": "请输入该提供商的 API Key",
  "No model available for this provider yet": "该提供商当前没有可用模型",
  "Could not save model configuration": "无法保存模型配置",
  "Onboarding keychain note": "凭据会保存在系统安全凭据存储中；不会写入项目文件。",
  "Model connection verified": "模型连接已验证",
  "Connection OK — this model is ready to use.": "连接成功，此模型可以使用。",
  "Connection OK — image generation is ready.": "连接成功，图像生成已就绪。",
  "Skip for now": "暂时跳过",
  "Hide": "隐藏",
  "Show": "显示",
  "Connect local CLI tools": "连接本地 CLI 工具",
  "If you verified a cloud model above, you can skip; otherwise connect at least one CLI.": "如果上一步已验证云端模型，可以跳过；否则请至少连接一个本地 CLI。",
  "Sidecar unavailable — start the orchestrator": "Sidecar 不可用，请启动编排服务",
  "Failed to connect tool": "连接工具失败",
  "Onboarding agent created": "已创建默认智能体：{name}",
  "No AI command-line tools detected yet": "尚未检测到 AI 命令行工具",
  "Install at least one recommended tool below (e.g. Claude Code, Ollama, or Aider). After installing in Terminal, click Rescan, then Connect. If you configured a cloud model, you can skip this step after verifying it.": "请至少安装下方一个推荐工具（如 Claude Code、Ollama 或 Aider）。在终端安装后点击重新扫描，再点击连接。如果已经配置并验证了云端模型，也可以跳过这一步。",
  "Run a command below in Terminal, then return here and click Rescan.": "在终端运行下方命令后，回到这里点击重新扫描。",
  "Recommended to install": "推荐安装",
  "More CLI options": "更多 CLI 选项",
  "Onboarding no cli installed": "未检测到已安装的 CLI 工具。",
  "Onboarding ollama no models": "已连接 Ollama，但尚未检测到本地模型。请先运行 ollama pull <model>。",
  "Workflows (Flow)": "工作流（Flow）",
  "Chain multiple Agents with a visual workflow.": "用可视化工作流串联多个智能体。",
  "Where to find it": "入口位置",
  "Quick setup": "快速设置",
  "Create a new workflow (or pick a built-in template)": "新建工作流，或选择一个内置模板",
  "Drag nodes onto the canvas and connect them": "把节点拖到画布上并连接",
  "Bind an AI Agent to each task node, then Save": "为每个任务节点绑定 AI 智能体，然后保存",
  "In chat: Workflow menu → select your flow → send a task": "在会话中打开工作流菜单，选择你的 Flow，然后发送任务",
  "Single-Agent chat does not need a Flow.": "单智能体会话不需要 Flow。",
  "Permission mode": "权限模式",
  "Only Ask before changes is active today. Other modes are still in development.": "当前仅启用“修改前询问”。其他模式仍在开发中。",
  "Ask before changes": "修改前询问",
  "Ask before file changes.": "修改文件前先请求确认。",
  "Edit automatically": "自动编辑",
  "Edit files automatically.": "自动编辑文件。",
  "Plan mode": "计划模式",
  "Plan before editing.": "编辑前先制定计划。",
  "Full access": "完全访问",
  "Run with fewer confirmations.": "以更少确认运行。",
  "Current default": "当前默认",
  "In development": "开发中",
  "Permission onboarding footnote": "后续可以在系统设置里调整权限模式。",
  "Ready to launch": "准备启动",
  "Review your setup, then open the workspace.": "检查当前设置，然后进入工作区。",
  "Active model": "当前模型",
  "Not configured (CLI path)": "未配置（使用 CLI 路径）",
  "Execution path": "执行路径",
  "Both cloud model and local CLI": "云端模型 + 本地 CLI",
  "Cloud model": "云端模型",
  "Local CLI": "本地 CLI",
  "Permission": "权限",
  "Default ask (read-only)": "默认询问（只读优先）",
  "Default agent": "默认智能体",
  "Full permission mode selection coming soon": "完整权限模式选择即将支持",
  "Keys stored in macOS Keychain": "密钥保存在 macOS Keychain 中",
  "Keys stored in Windows Credential Manager": "密钥保存在 Windows 凭据管理器中",
  "Keys stored securely by the operating system when supported": "在支持的平台上，密钥会保存在系统安全凭据存储中",

  // Header
  "Select workspace": "选择工作区",
  "Go Back": "返回",
  "Workspace": "工作空间",

  // General Settings Panel
  "Developer Profiles": "开发者角色配置",
  "Active Workspace Developer Profiles": "活跃工作空间开发者配置",
  "Create, switch, or customize roles with tailored system prompt instructions, memory logs, and API allowances.": "创建、切换或定制具有系统提示词、内存日志和 API 配额的角色。",
  "Switch Profile": "切换 角色",
  "ACTIVE PROFILE": "活跃 角色",
  "System Prompt / Directive": "系统 提示词指令",
  "Active Memory context": "活跃 内存上下文",
  "API Calls Allowance Limit": "API 调用次数限额",
  "Customize Active Instructions": "定制 System Prompt系统提示词指令",
  "Update Developer Settings": "更新开发者设置",
  "Save Custom Settings": "保存自定义 角色",

  // Agent Manager
  "AI Agents Registry": "AI 智能体注册表",
  "Orchestrate, edit, and launch autonomous specialized agent personas with custom tool allocations and constraints.": "编排、编辑和启动具有自定义 工具分配和约束的自治专业 智能体角色。",
  "Create Custom Agent": "创建自定义 智能体",
  "System Orchestrator Status: Active": "系统编排器状态: 活跃",
  "Active Agent Roles": "活跃 智能体角色",
  "Define and manage agents and system roles.": "定义与管理 智能体 及系统角色。",
  "Core Role Directive": "核心 指令/提示词",
  "Equipped Tools": "装备 工具",
  "Active Tasks Log": "活跃任务日志",
  "System Instruction Prompt": "系统指令 提示词",
  "Edit Agent Details": "编辑 智能体详情",
  "Add Custom Agent Profile": "添加 智能体属性",
  "Agent Name / Brand": "智能体名称",
  "Primary Purpose": "主要用途",
  "System Instructions prompt": "系统指令 提示词",
  "Associated LLM Model": "关联 LLM Model大模型",
  "Add Agent Persona": "新增 智能体",
  "Save Persona Settings": "保存 智能体设置",
  "Active Agent": "当前智能体",
  "Design uses the Model LLM, not CLI agents": "Design 使用模型 LLM 生成，不支持 CLI Agent",
  "Workflows are available in Coding mode": "工作流仅在 Coding 模式可用",
  "Select an AI Agent before sending.": "发送前请先选择智能体。",
  "Select an AI Agent or a Workflow before sending.": "发送前请选择智能体或工作流。",
  "builtin": "系统内置",
  "Edit Persona": "编辑 智能体角色",
  "Delete Persona": "删除 智能体角色",

  // Workflow panel
  "Workflows Standard Operating Procedures": "工作流 SOP标准作业程序",
  "Define, monitor, and execute step-by-step pipeline runs using automated agent interactions, validations, and artifact commits.": "通过自动化的 智能体交互、验证和 交付物提交，定义、监控并执行分步 管道流工作流。",
  "Create Custom SOP": "创建自定义 Workflows SOP标准作业程序",
  "Total Flows Loaded": "已加载 工作流总数",
  "Flow status:": "工作流状态:",
  "Flow Tasks SOP Progress": "任务进度",
  "Run Active SOP": "执行活跃 SOP",
  "Running Flow SOP Execution...": "正在执行 SOP中...",
  "Workflow execution successfully finished!": "工作流 SOP 执行成功完毕！",
  "Select a flow sequence to inspect execution.": "选择一个 工作流序列来检查执行状态。",
  "Step Details": "步骤详情",
  "Target Persona / Agent": "目标智能体",
  "Mock Output Artifact": "交付成果物",
  "View Generated Flow Output": "查看生成的 SOP结果",
  "Execution JSON Format": "执行格式 JSON",
  "Edit complex flows (checks, approvals, branches, loops) here; schema will be verified by Sidecar before saving.": "复杂流程（检查节点、人工审批、条件分支、循环）请在此编辑；保存前会经 Sidecar 校验。",
  "Failed to load": "加载失败",
  "Cannot connect to Sidecar": "无法连接 Sidecar",
  "Copy": "副本",
  "Saved to local workflow directory": "已保存到本机工作流目录",
  "Failed to save": "保存失败",
  "Step 1": "第一步",
  "Fill task instructions here": "在此填写任务说明",
  "Finish": "完成",
  "Failed to create workflow": "创建工作流失败",
  "Are you sure you want to delete this workflow?": "确定删除此工作流？",
  "Failed to delete": "删除失败",
  "Save as copy": "另存为副本",
  "Loading...": "加载中…",
  "Built-in template (Read-only)": "内置模板 · 只读",
  "User Workflow": "用户工作流",
  "Canvas editable (Simple linear workflow)": "支持画布编辑（简单线性流程）",
  "JSON mode only (Includes check/approval/branch)": "仅 JSON 模式（含检查/审批/分支）",
  "Canvas": "画布",
  "Complex workflow: please edit in JSON mode": "复杂流程：请用 JSON 编辑",
  "Built-in template: please save as copy after editing": "内置模板：编辑后请「另存为副本」",
  "Request failed": "请求失败",
  "JSON must contain id, nodes, and edges fields": "JSON 必须包含 id、nodes、edges 字段",
  "Confirm stopping the current run? This will interrupt the current AI Agent execution.": "确认停止当前运行？此操作将中断当前 AI 智能体执行。",
  "Next steps: select \"Bypass & Approve\", \"Reject & Redo\" below, or type instructions and click \"Retry\".": "下一步：在下方选择「Bypass & Approve」、「Reject & Redo」，或填写指令后 Retry。",


  // AI Tools page
  "AI Tools Registry & Sandbox": "AI 工具注册中心与沙箱",
  "Integrate, configure, and sand-box server-side functions and client APIs usable by connected agents for live task completion.": "集成、配置和沙盒化服务端 函数和客户端 API，供已连接的 智能体用于实时任务完成。",
  "Add Custom Tool Plugin": "添加自定义 工具插件",
  "Register New Tool Extension": "注册新 工具",
  "Tool Label": "工具标签",
  "Execution Hook": "执行 钩子",
  "Plugin Source Script": "插件 源码脚本",
  "Register Tool Plugin": "注册 工具",
  "Connected Tool Providers": "已连接的 工具提供方",
  "Developer sandbox execution test:": "开发者沙盒执行测试:",
  "Test Tool Execution": "测试 工具",
  "ACTIVE / ONLINE": "活跃上线",
  "SIMULATION OK": "模拟状态正常",
  "Active Sandbox Logs:": "活跃沙盒日志",

  // Skills registry page
  "Skills Library Index": "技能库索引",
  "Provision pre-defined behavior trees, domain patterns, and schema blueprints directly into agent contextual memory.": "直接将预定义的行为树、领域模式和 架构蓝图注入 智能体上下文 内存空间中。",
  "Add Domain Skill Capability": "添加领域 技能",
  "System Skills Loaded": "已加载系统 技能",
  "Register Skill Tree Extension": "注册 技能",
  "Skill Label / Name": "技能名称",
  "System Prompt Capability Overlay": "提示词叠加",
  "Inject Skill Override": "注入 技能",
  "Active Domain Skills": "活跃领域 技能",
  "Status": "状态",
  "LOADED / ONLINE": "已加载上线",

  // MCP Servers
  "Model Context Protocol Gateways": "Model Context Protocol (MCP) 服务网关",
  "Connect and manage secure remote contextual backends, SQL servers, filesystem sockets, and public API registries supporting the MCP protocol.": "连接并管理支持 MCP 协议的远程 上下文后端、SQL 数据库、文件系统套接字和公共 API 注册表。",
  "Add Remote MCP Hub Connecting Sockets": "连接远程 MCP 服务组",
  "Connected MCP Sockets": "已连接的 MCP 节点",
  "Open Connection Sockets": "打开连接节点",
  "Configure Remote MCP Server Node": "配置 MCP 节点",
  "Socket Hook Name": "节点钩子名称",
  "Transport Layer Mode": "传输层模式",
  "Endpoint Transport URL": "传输层 URL",
  "Register Node": "注册 MCP 节点",
  "ONLINE / ACTIVE": "在线活跃",
  "ACTIVE CONNECTION OK": "活跃连接正常",

  // Base Header
  "Single Agent": "单智能体",
  "Multi-Agent": "多智能体",
  "Workspace theme updated to:": "配色主题更新为:",
  "Active LLM Orchestrator": "活跃 LLM 编排器",

  // Theme presets
  "Pristine Light": "极简白",
  "Clean Hanken aesthetic with spacious negative spaces and absolute neutral shades.": "极简 Hanken 设计风格，配有宽敞的负空间和绝对纯净的自然色彩预设。",
  "Cyberpunk Neon": "赛博霓虹",
  "Vibrant high-contrast dark theme with fluorescent purple, cyan, pink accents, and absolute neon shadows.": "高饱和度对比的暗黑主题，配有荧光紫、青色、粉色点缀与霓虹灯阴影效果。",
  "Nordic Frost": "北欧冰霜",
  "Serene soft-blue cool theme inspired by cold scandinavian winter, slate cliffs, and pine forests.": "受北欧严冬、石板悬崖和松林启发的松绿与淡蓝色冰霜极简格调方案。",
  "Slate Charcoal": "石板深灰",
  "Ultra-professional eye-saving dark theme focused on graphite shades, subtle borders, and steel tones.": "超干练眼部友好的深灰墨黑方案，聚焦于石墨黑、细腻纤薄边框和冷钢色调设计。",
  "Terminal Green": "终端绿",
  "Vintage matrix-style monochrome retro aesthetic showcasing glowing emerald typography and pure terminal layouts.": "复古 Matrix 终端单色美学，展现发光祖母绿字符与纯粹极客命令行布局样式。",

  // Theme UI components
  "Active": "活跃启用",
  "Palette:": "配色:",
  "Background": "背景色",
  "Surface": "界面色",
  "Text color": "文字色",
  "Accent primary": "核心主调",
  "Select": "选择应用",
  "System": "系统",

  // Right panel & misc UI
  "Overview": "概览",
  "Files": "文件",
  "Changes": "变更",
  "Terminal": "终端",
  "Choose workflow": "选择工作流",
  "Workflows SOP": "工作流 SOP",
  "workflow": "工作流",
  "workflow_id": "工作流 ID",
  "active_node": "当前节点",
  "active_agent": "当前智能体",
  "status": "状态",
  "instruction": "指令",
  "Collapse Panel": "收起面板",
  "Expand Panel": "展开面板",
  "Close Panel": "关闭面板",
  "Collapse Sidebar": "折叠侧栏",
  "Expand Sidebar": "展开侧栏",
  "Session Token Analytics": "会话 Token 统计",
  "Total Tokens": "Token 总计",
  "Estimated Cost": "预估费用",
  "Token Distribution": "Token 分布",
  "Input vs Output": "输入 vs 输出",
  "Input": "输入",
  "Output": "输出",
  "Workspace Folder Structure": "工作区文件夹结构",
  "Preview file": "预览文件",
  "Preview Full": "完整预览",
  "Project Files": "项目文件",
  "Workflow agents": "工作流智能体",
  "No matching agents": "无匹配智能体",
  "Skills / Commands": "技能 / 命令",
  "Remove workflow": "移除工作流",
  "Model is determined by the selected workflow": "模型由所选工作流决定",
  "Model is bound on this agent": "模型绑定于当前智能体",
  "Failed to switch model.": "切换模型失败。",
  "Failed to save workflow": "保存工作流失败",
  "Save": "保存",
  "Drag to chat": "拖到聊天框",
  "idle": "空闲",
  "running": "运行中",
  "refining": "精修中",
  "awaiting_human": "待审批",
  "passed": "通过",
  "Completed": "已完成",
  "In progress": "进行中",
  "Failed": "失败",
  "failed": "失败",

  // Agent Manager — list, detail, create/edit modal
  "Create New AI Agent": "创建新 AI 智能体",
  "Edit Agent Settings": "编辑智能体设置",
  "Close": "关闭",
  "Module 1": "模块 1",
  "Module 2": "模块 2",
  "Module 3": "模块 3",
  "Module 4": "模块 4",
  "Module 5": "模块 5",
  "Identity & Driving Engine": "身份与驱动引擎",
  "Agent Name": "智能体名称",
  "e.g. Orchestration Dispatcher v2.0": "例如：编排调度器 v2.0",
  "Agent Type": "智能体类型",
  "Built-in agent uses Clutch models. Pick a default model below or switch at runtime in chat.": "内置智能体使用 Clutch 模型。可在下方选择默认模型，或在对话中运行时切换。",
  "No CLI tools are connected yet. Open Settings → AI Tools, connect a tool, and run Auto-configure to add more agent types here.": "尚未连接 CLI 工具。请打开 设置 → AI 工具，连接工具并运行自动配置以添加更多智能体类型。",
  "Use global default model": "使用全局默认模型",
  "No models configured yet. Add API keys or image models under Settings → Models first.": "尚未配置模型。请先在 设置 → 模型配置 中添加 API Key 或图像模型。",
  "No models configured yet. Add API keys or image/video models under Settings → Models first.": "尚未配置模型。请先在 设置 → 模型配置 中添加 API Key 或图像/视频模型。",
  "Clutch agents run on Sidecar models (chat or image). Leave empty to follow the global model in chat.": "Clutch 智能体运行在 Sidecar 模型上（对话或图像）。留空则跟随对话中的全局模型。",
  "Clutch agents run on Sidecar models (chat, image, or video). Leave empty to follow the global model in chat.": "Clutch 智能体运行在 Sidecar 模型上（对话、图像或视频）。留空则跟随对话中的全局模型。",
  "Chat models": "对话模型",
  "Image models": "图像模型",
  "Video models": "视频模型",
  "Ollama Model": "Ollama 模型",
  "Ollama is not running.": "Ollama 未运行。",
  "Make sure the Ollama desktop application is open or that the Ollama daemon is running in the background.": "请确保 Ollama 桌面应用已打开，或后台 Ollama 守护进程正在运行。",
  "Starting Ollama...": "正在启动 Ollama…",
  "Launch Ollama Service": "启动 Ollama 服务",
  "No local models found. Ensure Ollama is running and run ollama pull <model> first (e.g., ollama pull qwen2.5-coder).": "未找到本地模型。请确保 Ollama 已运行，并先执行 ollama pull <model>（例如 ollama pull qwen2.5-coder）。",
  "Select which locally installed Ollama model this agent uses at runtime.": "选择此智能体运行时使用的本地 Ollama 模型。",
  "Short Description": "简短描述",
  "Summarize the core execution task of this operational entity...": "概括此执行单元的核心任务…",
  "System Persona & Soul": "系统角色与人设",
  "System Prompt / Directive Summary": "系统提示词 / 指令摘要",
  "Enter basic setup persona details...": "输入基础人设与指令…",
  "Tips": "提示",
  "Agent persona tips": "此处仅写 1–2 行核心人设（例如：「你是一名严格的安全审计员。」）。详细规范与检查清单请在全局 设置 中配置，并通过 模块 3 挂载本地专业手册。",
  "Attach Agent Skills": "挂载智能体技能",
  "Local-First": "本地优先",
  "Linked Agent Skills Manuals": "已关联技能手册",
  "Only active skills from your global directory are available below.": "下方仅显示全局目录中已激活的技能。",
  "Attach Skills": "挂载技能",
  "Fuzzy Search Active Specs": "模糊搜索已激活规范",
  "Done": "完成",
  "Fuzzy search active skills (e.g. secure, performance)...": "模糊搜索技能（如 secure、performance）…",
  "No globally active skills found. Please navigate to the left-side settings Skills Registry pane and activate some SKILL.md rules first!": "未找到全局激活的技能。请先在左侧 设置 → 技能注册表 中激活 SKILL.md 规则。",
  "No matching active skills found.": "没有匹配的技能。",
  "No manual skills attached. Click \"Attach Skills\" to pick dynamic specifications.": "未挂载技能手册。点击「挂载技能」选择规范。",
  "MCP Hub Server Bindings": "MCP 服务网关绑定",
  "Bind MCP servers from Settings → MCP Hub. Used when this agent runs on Clutch models.": "从 设置 → MCP 服务网关 绑定 MCP 服务。用于 Clutch 模型智能体。",
  "No enabled MCP servers in Hub. Add servers under Settings → MCP Hub first.": "网关中没有已启用的 MCP 服务。请先在 设置 → MCP 服务网关 中添加。",
  "Bound": "已绑定",
  "tools": "工具",
  "Claude Code (Local CLI) agents use Skills and MCP installed in your local Claude Code environment — not Clutch MCP Hub bindings.": "Claude Code（本地 CLI）智能体使用本地 Claude Code 环境中的技能与 MCP，而非 Clutch MCP 网关绑定。",
  "Deliverables Config & State Update Rules": "交付物配置与状态更新规则",
  "Define the scheduled file assets produced by this agent. If orchestrators find these assets absent, rejection alerts trigger:": "定义此智能体产出的计划文件资产。编排器若发现缺失将触发拒绝告警：",
  "File name (e.g. results.json)": "文件名（如 results.json）",
  "+ Add List File": "+ 添加文件",
  "Enter file template specification markup inside...": "输入文件模板规范…",
  "Remove deliverable": "移除交付物",
  "Create AI Agent": "创建 AI 智能体",
  "Save Configuration": "保存配置",
  "Dismiss View": "关闭预览",
  "Back to List": "返回列表",
  "Edit Settings": "编辑设置",
  "Role System Specifications": "角色系统规范",
  "Agent Details": "智能体详情",
  "NAME": "名称",
  "AI Agent Controller": "AI 智能体控制台",
  "Display the operational directive frameworks and output manifests loaded in the execution sandbox.": "展示执行沙箱中加载的操作指令框架与输出清单。",
  "Create Agent": "创建智能体",
  "No agents configured. Create one to define prompts, deliverables, and execution settings.": "暂无智能体。创建一个以定义提示词、交付物与执行设置。",
  "Edited:": "编辑于：",
  "Deliverables": "交付物",
  "Skills": "技能",
  "View details": "查看详情",
  "Edit settings": "编辑设置",
  "Delete agent": "删除智能体",
  "No associated deliverablesconfigured.": "未配置关联交付物。",

  // Workflow orchestration
  "Workflow Orchestration": "工作流编排",
  "Design and manage cooperative multi-agent state pipelines.": "设计并管理多智能体协作状态管道。",
  "Active SOP Workflows": "活跃 SOP 工作流",
  "Select or create a workflow": "选择或创建工作流",
  "Flow Name": "工作流名称",
  "e.g. Design & Prototype SOP": "例如：设计与原型 SOP",
  "Briefly state the goal of this pipeline...": "简要说明此管道的目标…",
  "Flow Icon Representation": "工作流图标",
  "Tree": "树形",
  "Code": "代码",
  "Sync": "同步",
  "Video": "视频",
  "Play": "播放",
  "Pause": "暂停",
  "Download": "下载",
  "Downloading…": "下载中…",
  "Download video": "下载视频",
  "Generated video": "生成的视频",
  "Could not play video.": "无法播放视频。",
  "Could not load video.": "无法加载视频。",
  "Download failed.": "下载失败。",
  "Open video in browser": "在浏览器中打开视频",
  "Deploy": "部署",
  "Console": "控制台",
  "API": "API",
  "SOP Mapping": "SOP 映射",
  "Edit Node": "编辑节点",
  "New Node": "新建节点",
  "Node Name": "节点名称",
  "e.g. Asset Gathering": "例如：资产收集",
  "Assigned Agent": "指定智能体",
  "Select an agent…": "选择智能体…",
  "No agents configured. Create agents in the Agents panel first.": "尚未配置智能体。请先在智能体面板中创建。",
  "AI Tool / Type:": "AI 工具 / 类型：",
  "Description:": "描述：",
  "Description": "描述",
  "Description / Instructions": "描述 / 指令",
  "Task instructions...": "任务说明…",
  "JSON": "JSON",

  // Models manager
  "Choose which model Clutch uses for chat and workflows.": "选择 Clutch 用于对话与工作流的模型。",
  "Add": "新增",
  "Add model": "添加模型",
  "Add text model": "新增文本模型",
  "Add custom text model": "添加自定义文本模型",
  "Register an OpenAI-compatible chat endpoint (e.g. Agnes 2.0 Flash).": "注册 OpenAI 兼容的对话端点（如 Agnes 2.0 Flash）。",
  "My Text Model": "我的文本模型",
  "Save text model": "保存文本模型",
  "Built-in provider — enter your API key to enable this model.": "内置提供商 — 填写 API Key 即可启用对应模型。",
  "Custom gateway — non-built-in model. Fill in the endpoint details below.": "自定义网关（非内置模型）— 请填写下方端点信息。",
  "Could not save model.": "无法保存模型。",
  "Base URL and model id are required for custom gateways.": "自定义网关须填写 Base URL 和模型 ID。",
  "Add video model": "添加视频模型",
  "Add custom video model": "添加自定义视频模型",
  "Register a text-to-video endpoint (e.g. Agnes Video V2.0). Generation is async — poll by video_id.": "注册文生视频端点（如 Agnes Video V2.0）。生成为异步任务，请用 video_id 查询。",
  "My Video Model": "我的视频模型",
  "Save video model": "保存视频模型",
  "Could not add video model.": "无法添加视频模型。",
  "Add image model": "添加图像模型",
  "Add API key": "添加 API Key",
  "Add custom image model": "添加自定义图像模型",
  "Register a text-to-image endpoint without editing code. Use Agnes or any OpenAI-compatible gateway.": "无需改代码即可注册文生图端点。可使用 Agnes 或任意 OpenAI 兼容网关。",
  "Display name": "显示名称",
  "My Image Model": "我的图像模型",
  "API model id": "API 模型 ID",
  "Base URL": "Base URL",
  "API key provider": "API Key 提供方",
  "Image backend": "图像后端",
  "Auto-detect from URL": "根据 URL 自动检测",
  "Agnes Image API": "Agnes 图像 API",
  "OpenAI-compatible /v1/images/generations": "OpenAI 兼容 /v1/images/generations",
  "API key (optional)": "API Key（可选）",
  "Save key for the selected provider": "为所选提供方保存 Key",
  "Save image model": "保存图像模型",
  "Saving…": "保存中…",
  "Update API key": "更新 API Key",
  "Saved in Clutch and used for built-in models of this provider.": "保存在 Clutch 中，供该提供方的内置模型使用。",
  "Provider": "提供方",
  "API key": "API Key",
  "Remove saved key": "移除已保存 Key",
  "Removing…": "移除中…",
  "Remove": "移除",
  "Remove model": "移除模型",
  "Edit model": "编辑模型",
  "Edit custom model": "编辑自定义模型",
  "Show API key": "显示 API Key",
  "Hide API key": "隐藏 API Key",
  "Current model": "当前模型",
  "None selected": "未选择",
  "Pick a model below or add an API key to get started.": "在下方选择模型，或添加 API Key 开始使用。",
  "Testing connection…": "正在测试连接…",
  "Ready to use.": "可以使用。",
  "Last test failed — fix the key or choose another model.": "上次测试失败 — 请修正 Key 或选择其他模型。",
  "Not tested yet — press Test when you want to verify.": "尚未测试 — 需要时点击测试进行验证。",
  "Available models": "可用模型",
  "listed": "项",
  "Loading models…": "正在加载模型…",
  "No models yet — add an API key or import from CC Switch.": "暂无模型 — 请添加 API Key 或从 CC Switch 导入。",
  "Image": "图像",
  "Custom": "自定义",
  "Needs key": "需要 Key",
  "In use": "使用中",
  "Testing…": "测试中…",
  "Ready": "就绪",
  "Connection failed": "连接失败",
  "Connection timed out — check your network or try again.": "连接超时 — 请检查网络后重试。",
  "Connection timed out — the provider may be overloaded. Retest, switch to another model, or try again later.": "连接超时 — 服务商可能繁忙。请重试、切换其他模型，或稍后再试。",
  "Test connection": "测试连接",
  "Retest connection": "重新测试",
  "Testing connection": "正在测试连接",
  "Change {provider} key": "更改 {provider} Key",
  "Already use CC Switch?": "已使用 CC Switch？",
  "Importing…": "导入中…",
  "Import models": "导入模型",
  "Remove custom model permanently": "此自定义模型将被永久删除。",
  "Hide CC Switch imported models": "CC Switch 导入的模型将从列表隐藏，可点击「导入模型」恢复。",
  "Hide built-in model": "内置模型将从列表隐藏，可通过编辑 models.json 恢复。",
  "Remove from model list?": "从模型列表中移除",

  // Agent capability tabs (Models / MCP / Skills)
  "More": "更多",
  "Coming soon": "即将推出",
  "Under development": "开发中",
  "Dismiss": "关闭",
  "Scanning…": "扫描中…",
  "Scan complete — {models} models, {providers} credential providers found.": "扫描完成 — 发现 {models} 个模型、{providers} 个凭证提供方。",
  "Scan complete — {count} providers found.": "扫描完成 — 发现 {count} 个提供方。",
  "Scanning OpenCode configuration…": "正在扫描 OpenCode 配置…",
  "Scanning Claude Code configuration…": "正在扫描 Claude Code 配置…",
  "Models used by the OpenCode CLI (opencode run). This is separate from OpenCode Zen models configured for the Clutch built-in agent.": "OpenCode CLI（opencode run）使用的模型。与 Clutch 内置智能体的 OpenCode Zen 模型配置相互独立。",
  "Models used by the Claude Code CLI subprocess. Clutch does not inject Models Manager settings into Claude agents.": "Claude Code CLI 子进程使用的模型。Clutch 不会将 Models Manager 设置注入 Claude 智能体。",
  "OpenCode config docs": "OpenCode 配置文档",
  "Not detected": "未检测到",
  "Default agent": "默认智能体",
  "Config": "配置",
  "Credentials": "凭证",
  "No opencode.json found. Run opencode once or create ~/.config/opencode/opencode.json.": "未找到 opencode.json。请先运行 opencode 一次，或创建 ~/.config/opencode/opencode.json。",
  "Configured credentials": "已配置凭证",
  "Connected": "已连接",
  "Available models": "可用模型",
  "Select a model to set the OpenCode CLI default. Free built-in models are included.": "选择模型以设为 OpenCode CLI 默认模型。包含免费内置模型。",
  "Install the opencode CLI on PATH to switch models from Clutch.": "请将 opencode CLI 加入 PATH，以便在 Clutch 中切换模型。",
  "Free": "免费",
  "Use model": "使用此模型",
  "Failed to switch model.": "切换模型失败。",
  "CC Switch providers": "CC Switch 提供方",
  "CC Switch app data detected. Install the cc-switch CLI on PATH to switch providers from Clutch, or switch in the CC Switch desktop app.": "已检测到 CC Switch 应用数据。若要从 Clutch 切换提供方，请将 cc-switch CLI 加入 PATH，或在 CC Switch 桌面应用中切换。",
  "Install the cc-switch CLI on PATH to switch providers from Clutch, or use the CC Switch desktop app.": "请将 cc-switch CLI 加入 PATH 以便在 Clutch 中切换提供方，或使用 CC Switch 桌面应用。",
  "cc-switch CLI detected — you can switch providers below.": "已检测到 cc-switch CLI — 可在下方切换提供方。",
  "CC Switch database detected": "已检测到 CC Switch 数据库",
  "CC Switch not found — showing ~/.claude/settings.json only": "未找到 CC Switch — 仅显示 ~/.claude/settings.json",
  "Repair CC Switch config": "修复 CC Switch 配置",
  "Repairing…": "修复中…",
  "Failed to repair Claude Code settings.": "修复 Claude Code 配置失败。",
  "Activate a provider to change the Claude Code CLI model.": "激活提供方以更改 Claude Code CLI 模型。",
  "Read-only list. Switch providers in CC Switch or install cc-switch CLI for in-app switching.": "只读列表。请在 CC Switch 中切换，或安装 cc-switch CLI 以在 Clutch 内切换。",
  "Set up cc-switch CLI": "一键配置",
  "Installing…": "安装中…",
  "Failed to install cc-switch CLI.": "安装 cc-switch CLI 失败。",
  "Install package is ready — click to finish setup.": "安装包已就绪，点击即可完成配置。",
  "Claude Code provider switching uses CC Switch. OpenCode uses its own native config and does not require cc-switch CLI.": "Claude Code 切换 provider 依赖 CC Switch；OpenCode 使用自身原生配置，无需 cc-switch CLI。",
  "This agent uses native {label} skills bundled with the CLI — not Clutch Skills Registry bindings.": "该智能体使用 {label} 自带技能，不由 Clutch Skills Registry 绑定。",
  "This agent uses native {label} MCP servers — not Clutch MCP Hub bindings.": "该智能体使用 {label} 自带 MCP 服务，不由 Clutch MCP Hub 绑定。",
  "Hide details": "收起详情",
  "Choose folder": "选择文件夹",
  "No folder selected": "未选择文件夹",
  "Could not open folder picker.": "无法打开文件夹选择器。",
  "No MCP servers found in native config. Claude Code uses ~/.claude.json and project .mcp.json — Cursor MCP (~/.cursor/mcp.json) is separate.": "未在原生配置中找到 MCP。Claude Code 使用 ~/.claude.json 与项目根目录 .mcp.json；Cursor 的 MCP（~/.cursor/mcp.json）是另一套配置。",
  "Disabled for this agent": "未对该智能体启用",
  "Hidden folders (e.g. ~/.cursor/skills): type the path directly, or press Cmd+Shift+. in the picker to show hidden files.": "隐藏目录（如 ~/.cursor/skills）可直接输入路径；选择器已默认显示隐藏文件夹，也可按 Cmd+Shift+. 切换。",
  "{label} uses built-in CLI skills. See the Skills Registry page for details.": "{label} 自带 Skills 能力，详情请查看 Skills Registry 页面。",
  "{label} uses built-in CLI MCP servers. See the MCP Server Hub page for details.": "{label} 自带 MCP 能力，详情请查看 MCP Server Hub 页面。",
  "Activate": "激活",
  "Switching…": "切换中…",
  "Failed to switch provider.": "切换提供方失败。",
  "Claude settings preview": "Claude 设置预览",
  "No model id": "无模型 ID",
  "More agent integrations are under development. Claude Code and OpenCode are available today; others will appear here when ready.": "更多智能体集成正在开发中。目前已支持 Claude Code 与 OpenCode；其他工具就绪后将显示在此处。",
  "Codex": "Codex",
  "Aider": "Aider",
  "CodeBuddy": "CodeBuddy",
  "Antigravity": "Antigravity",
  "Rivet": "Rivet",
  "Ollama": "Ollama",
  "OpenCode": "OpenCode",
  "Claude Code": "Claude Code",

  // MCP Server Hub
  "Register stdio or SSE MCP servers alongside the built-in workspace filesystem server. User servers persist in Application Support and connect when agents run.": "注册 stdio 或 SSE MCP 服务，与内置工作区文件系统服务并存。用户服务保存在 Application Support，智能体运行时连接。",
  "CONNECTED": "已连接",
  "MCP TOOLS": "MCP 工具",
  "Edit Raw Config JSON": "编辑原始 JSON 配置",
  "Save JSON Config": "保存 JSON 配置",
  "Register MCP Server": "注册 MCP 服务",
  "Import from Claude": "从 Claude 导入",
  "Edit raw JSON": "编辑原始 JSON",
  "+ Register Node": "+ 注册节点",
  "Loading MCP status…": "正在加载 MCP 状态…",
  "No MCP servers available.": "暂无 MCP 服务。",
  "Exposed Tools:": "暴露的工具：",
  "STATUS": "状态",
  "TOOLS": "工具",
  "Online": "在线",
  "Configured": "已配置",
  "Offline": "离线",

  // Skills Registry
  "Global Skills Registry": "全局技能注册表",
  "Mount directories skills hint": "挂载包含 SKILL.md 的目录。Clutch 会在刷新时自动检测 ~/.cursor/skills-cursor 与工作区 skills/ 文件夹。",
  "Search Paths": "搜索路径",
  "Paths stored in Application Support and scanned on refresh.": "路径保存在 Application Support，刷新时扫描。",
  "Rescan": "重新扫描",
  "Loading skills registry…": "正在加载技能注册表…",
  "No skill directories mounted.": "尚未挂载技能目录。",
  "Unmount directory": "卸载目录",
  "e.g. ~/.cursor/skills/": "例如：~/.cursor/skills/",
  "+ Mount Root": "+ 挂载根目录",
  "Discovered Skills": "已发现技能",
  "FOUND": "项",
  "No skills discovered yet.": "尚未发现技能。",
  "Active globally": "全局激活",
  "Inactive": "未激活",

  // AI Tools
  "AI Tools Integration": "AI 工具集成",
  "Detected local AI CLIs on this machine. Connect only tools you want Clutch to route to.": "检测本机 AI 命令行工具。仅连接你希望 Clutch 调度的工具。",
  "No AI command-line tools installed yet": "尚未安装 AI 命令行工具",
  "Install CLI tools hint": "请使用下方安装指南至少安装一个工具（如 Claude Code、Ollama、Codex 或 Antigravity），然后点击连接。",
  "Scanning local toolchains…": "正在扫描本地工具链…",
  "No supported AI tools detected on this machine.": "本机未检测到支持的 AI 工具。",
  "Install CLI rescan hint": "安装 AI CLI（如 claude、codex、agy、ollama）后重新扫描。",
  "Connected": "已连接",
  "No AI tools connected yet.": "尚未连接 AI 工具。",
  "Unconfigured": "未配置",
  "Available to connect": "可连接",
  "Not installed": "未安装",
  "Connect": "连接",
  "Disconnect": "断开",
  "Auto-configure": "自动配置",
  "Show install guide": "显示安装指南",
  "Copy command": "复制命令",
  "Copied": "已复制",

  // Agent detail (remaining)
  "DESCRIPTION": "描述",
  "AGENT TYPE": "智能体类型",
  "OLLAMA MODEL": "Ollama 模型",
  "LAST MODIFIED": "最后修改",
  "Attached Skills Manuals": "已挂载技能手册",
  "MCP Hub Servers": "MCP 服务网关",
  "MODEL": "模型",
  "Auto-select best local model": "自动选择最佳本地模型",
  "No linked professional skills attached to this agent manual.": "此智能体未挂载关联技能。",
  "Visit Website": "访问网站",
  "No skills loaded": "未加载技能",
  "No matches": "无匹配项",
  "No workspace files loaded": "未加载工作区文件",
  "Stop": "停止",

  // Chat input misc
  "Drop to attach": "拖放以附加",
  "No agents in this workflow": "此工作流中无智能体",
  "No sessions yet": "暂无会话",
  "Sessions": "会话",
  "Filter files...": "筛选文件…",
  "Attach": "附加",
  "Add attachment": "添加附件",

  // Workflow node editor extras
  "Source Flows (Incoming Upstream Nodes)": "来源流程（上游节点）",
  "Next Flows (Connected Downstream Nodes)": "下游流程（连接节点）",
  "No other steps in this workflow yet.": "此工作流中尚无其他步骤。",
  "Tip: Toggle checks above or drag lines directly on the workflow canvas.": "提示：可在上方勾选，或在工作流画布上直接拖拽连线。",
  "New Step": "新步骤",
  "Edit node": "编辑节点",
  "Delete node": "删除节点",

  // MCP extras
  "Enable": "启用",
  "Disable": "禁用",
  "MCP server registered.": "MCP 服务已注册。",
  "MCP raw config saved.": "MCP 原始配置已保存。",
  "Imported configurations from local Claude setups.": "已从本地 Claude 配置导入。",
  "Sidecar unavailable — cannot read MCP status.": "Sidecar 不可用 — 无法读取 MCP 状态。",

  // Skills extras
  "Directory is already mounted": "该目录已挂载",
  "Directory mounted. No SKILL.md files found yet.": "目录已挂载，尚未发现 SKILL.md 文件。",
  "Mounted and discovered {count} skill(s).": "已挂载并发现 {count} 个技能。",
  "Sidecar unavailable — cannot load skills registry.": "Sidecar 不可用 — 无法加载技能注册表。",
  "Failed to update skill — Sidecar may be offline.": "更新技能失败 — Sidecar 可能离线。",
  "Toggle global skill": "切换全局技能",

  // AI Tools extras
  "Disconnecting…": "断开中…",
  "Connecting…": "连接中…",
  "Connect Tool": "连接工具",
  "Hide Install Guide": "隐藏安装指南",
  "Install Guide": "安装指南",
  "CLI": "CLI",
  "Client": "客户端",
  "Sidecar unavailable — start the orchestrator to scan local tools.": "Sidecar 不可用 — 请启动编排器以扫描本地工具。",

  // AI Tools section headers
  "Detected (not connected)": "已检测（未连接）",
  "All detected tools are connected.": "所有已检测工具均已连接。",
  "Available to Install": "可安装",
  "Recommended to Install": "推荐安装",
  "Install guides below list tested CLIs only; other whitelist tools appear here once installed.": "下方安装指引仅列出经 Clutch 验证的 CLI；白名单中的其他工具在安装后会自动出现在上方。",
  "All supported AI tools are installed.": "所有支持的 AI 工具均已安装。",
  "Not Installed": "未安装",
  "Configuring…": "配置中…",
  "Auto Config": "自动配置",
  "To start utilizing agent-based coding, please install at least one tool (e.g. Claude Code, Ollama, Codex, or Antigravity) using the installation guides below, and then click connect.": "请使用下方安装指南至少安装一个工具（如 Claude Code、Ollama、Codex 或 Antigravity），然后点击连接。",
  "Install at least one recommended tool below (e.g. Claude Code, Ollama, Codex, or Antigravity). After installing in Terminal, click Rescan, then Connect. If you configured a cloud model, you can skip this step after verifying it.": "请至少安装下方推荐工具之一（如 Claude Code、Ollama、Codex 或 Antigravity）。在终端安装后点击重新扫描，再连接。若已配置云模型，验证通过后可跳过此步。",
  "Install an AI CLI (e.g. claude, codex, agy, ollama), then rescan.": "安装 AI CLI（如 claude、codex、agy、ollama）后重新扫描。",

  // Models error messages
  "Cannot reach Clutch sidecar — start the backend on port 8124 (dev) or reopen the packaged app.": "无法连接 Clutch Sidecar — 开发环境请启动 8124 端口后端，或重新打开打包应用。",
  "Sidecar session expired — quit Clutch (Cmd+Q) and reopen the app.": "Sidecar 会话已过期 — 请完全退出 Clutch（Cmd+Q）后重新打开。",
  "Sidecar backend error — quit Clutch (Cmd+Q) and reopen the app.": "Sidecar 后端错误 — 请完全退出 Clutch（Cmd+Q）后重新打开。",
  "Connection test failed.": "连接测试失败。",
  "Could not add image model.": "无法添加图像模型。",
  "Could not switch to this model.": "无法切换到此模型。",
  "Could not save API key.": "无法保存 API Key。",
  "Could not remove saved key.": "无法移除已保存 Key。",
  "CC Switch import failed.": "CC Switch 导入失败。",
  "Remove the saved API key for {provider}?": "移除 {provider} 的已保存 API Key？",
  "Remove {name} from your model list?": "从模型列表中移除 {name}？",
};


export const translateRunStatus = (status: string, language: Language): string => {
  if (language === 'en') return status;
  const key = status.trim().toLowerCase();
  return zhTranslations[key] ?? status;
};

// Fallback translator for keys not in the dictionary.
export const translateText = (text: string, language: Language): string => {
  if (language === 'en') return text;

  const trimmed = text.trim();
  if (zhTranslations[trimmed]) {
    return zhTranslations[trimmed];
  }

  const termsMap: Array<{ regex: RegExp; replacement: string }> = [
    { regex: /\bMulti-Agent\b/gi, replacement: '多智能体' },
    { regex: /\bSingle-Agent\b/gi, replacement: '单智能体' },
    { regex: /\bWorkflows?\b/gi, replacement: '工作流' },
    { regex: /\bAgents?\b/gi, replacement: '智能体' },
    { regex: /\bModels?\b/gi, replacement: '模型' },
    { regex: /\bPrompts?\b/gi, replacement: '提示词' },
    { regex: /\bSkills?\b/gi, replacement: '技能' },
    { regex: /\bTools?\b/gi, replacement: '工具' },
  ];

  let result = trimmed;
  for (const { regex, replacement } of termsMap) {
    result = result.replace(regex, replacement);
  }
  return result;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('workspace_lang');
    return (saved === 'zh' || saved === 'en') ? saved : 'en';
  });

  useEffect(() => {
    void fetchLanguagePreference()
      .then((lang) => {
        setLanguageState(lang);
        localStorage.setItem('workspace_lang', lang);
      })
      .catch(() => {});
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('workspace_lang', lang);
    void saveLanguagePreference(lang).catch(() => {});
  };

  const t = (key: string): string => {
    return translateText(key, language);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
